const BlogData = [
    {
      id: 1,
      title: "The Art of Mindfulness",
      author: "Jane Doe",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3RggQXhdkSdrAaZcN7BjMs1B4YudFLSe9Cw&s",
      description: "Discover how mindfulness can improve your daily life with practical tips and insights.",
      type: "Lifestyle",
    },
    {
      id: 2,
      title: "Exploring the Galaxy: The Future of Space Travel",
      author: "John Smith",
      image: "https://bigthink.com/wp-content/uploads/2023/02/AdobeStock_558949687.jpg",
      description: "A look into the latest advancements in space exploration and what's on the horizon.",
      type: "Science",
    },
    {
      id: 3,
      title: "Top 10 JavaScript Frameworks for Developers",
      author: "Emily Johnson",
      image: "https://d2ms8rpfqc4h24.cloudfront.net/Stack_Overflow_Survey_for_React_js_Framework_8734b9dc07.jpg",
      description: "A comprehensive guide to the best JavaScript frameworks for modern web development.",
      type: "Technology",
    },
    {
      id: 4,
      title: "A Journey Through Italian Cuisine",
      author: "Chef Mario",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgJXocwRRMm2IxpDNGGAKHCdWUWFCLLlCSGQ&s",
      description: "Explore the rich flavors and recipes of traditional Italian cooking.",
      type: "Food",
    },
    {
      id: 5,
      title: "The Impact of Climate Change on Wildlife",
      author: "Dr. Anna Green",
      image: "https://media.licdn.com/dms/image/v2/D5612AQGtaXpwXYeKLg/article-cover_image-shrink_600_2000/article-cover_image-shrink_600_2000/0/1700202492694?e=2147483647&v=beta&t=ZGti6p6e8a5aOoaxbC1Dx7OavJJBXoMpZRBOEXCT8ig ",
      description: "How climate change is affecting ecosystems and what we can do to help.",
      type: "Environment",
    },
    {
      id: 6,
      title: "The Evolution of Modern Art",
      author: "Sophia Clark",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu5-Jp-5OLS67NVKrN3PIOlcFFOLnQtvkShg&s",
      description: "An exploration of how art has evolved over the last century.",
      type: "Art",
    },
    {
      id: 7,
      title: "10 Must-Visit Destinations for 2024",
      author: "Mike Traveler",
      image: "https://i.ytimg.com/vi/OCzzN8VZgfY/maxresdefault.jpg",
      description: "A curated list of breathtaking places to add to your travel bucket list.",
      type: "Travel",
    },
    {
      id: 8,
      title: "The Future of Artificial Intelligence",
      author: "Dr. Alan Turing",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2u2KHNpswql4qHwdEz1BuCnF1fFESUJiLnw&s",
      description: "A deep dive into how AI is shaping our world and its potential in the future.",
      type: "Technology",
    },
    {
      id: 9,
      title: "Mastering Yoga for Better Health",
      author: "Lisa Zen",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7jQYoDrK3N2UWKmQ_-LYTv_iGYT2U9Rhr3A&s",
      description: "Learn the benefits of yoga and how to incorporate it into your daily routine.",
      type: "Lifestyle",
    },
    {
      id: 10,
      title: "Breaking Down the Basics of Investing",
      author: "Mark Investor",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPjMUlZZwaNhbBNNbEMtcNGtF8xANepfoyhw&s               ",
      description: "A beginner's guide to understanding the world of investments and making smart choices.",
      type: "Finance",
    },
  ];
  
  export default BlogData;
  